<!doctype html>
<html>
  <head>
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

       <!-- Bootstrap CSS -->
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        .row div    {padding: 20px 10px; 
                     border: 8px solid white;}
        .col-md-6    {padding: 5px 5px 5px 5px;}
        body        {background: white;}
        nav         {background: lightgrey;
                     color: black;
                     z-index: 80;}
        footer      {margin-top: 20px;
                     height: 90px;
                     text-align: center;}
        a           {font-family: Sacramento, cursive;
                     font-size: 50px;
                     color: lightseagreen;}             
        header      {margin-bottom: 80px;
                     padding-top: 20px;
                     height: 170px;
                     text-align: center;}
        header a    {font-family: Arial, Helvetica, sans-serif;
                     font-size: 20px;
                     color: darkgray;}             
        h1          {font-family: Sacramento, cursive;
                     font-size: 90px;
                     color: lightseagreen}
        p a         {font-family: Arial, Helvetica, sans-serif;
                     font-size: 50px;
                     color: darkgray;}  
        p           {text-align: center;}   
        a:hover     {color: grey;
                     text-decoration: none;}         
        </style>

<title>lonelysocks</title>
</head>

<body>

        <header style="background: lightgrey"> 

                <h1> lonelysocks</h1>
           
           <nav class="navbar navbar-expand-md navbar-light bg-light">
                   <a class="navbar-brand" href="#"><!--Logo einfügen maybe?--></a>
                   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                   </button>
                   <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                     <div class="navbar-nav">
                       <a class="nav-item nav-link" href="index.php?page=home">Home <span class="sr-only">(current)</span></a>
                       <a class="nav-item nav-link" href="index.php?page=login">Login</a>
                       <a class="nav-item nav-link" href="index.php?page=warenkorb">Warenkorb</a>
                     </div>
                   </div>
                 </nav>               
        </header>

<body> 
<form>
        <div class="container">

                <div class="row" style="background: lightseagreen">
                    <div class="col-md-6"> 
                        E-Mail: <br>
                        <input type="text"> 
                    </div>
                    <div class="col-md-6"> 
                            Passwort: <br>
                            <input type="text"> 
                        </div>
                    <div class="col-md-6"> 
                     <br>   <button> Login </button>
                    </div>
                    <div class="col-md-6"> <br>
                        
                                <button > <a href="index.php?page=register">Registrieren  </a></button>
                       
                            <!---->
                           </div>
                </div>
               
        </div>
</form>

</body>