<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link type="text/css" rel="stylesheet" media="screen" href="../css/Bootstrap.css"/>
   <link type="text/css" rel="stylesheet" media="screen" href="../css/Style.css"/>
   <link href= "https://fonts.google.com/specimen/Open+Sans" rel="stylesheet" type="text/css">
  

    <title>Produktansicht</title>
  </head>
  <body>

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
        
                <div id="js-gallery" class="gallery">

                        <!--Gallery Hero-->
                        <div class="gallery__hero">
                          <img src="../images/1.png">
                        </div>
                        <!--Gallery Hero-->
                    
                        <!--Gallery Thumbs-->
                        <div class="gallery__thumbs">
                            <a href="../images/1.png" data-gallery="thumb" class="is-active">
                              <img src="../images/1.png">
                            </a>
                            <a href="../images/2.png" data-gallery="thumb">
                              <img src="../images/2.png">
                            </a>
                            <a href="../images/3.png" data-gallery="thumb">
                              <img src="../images/3.png">
                            </a>
                        </div>
                        <!--Gallery Thumbs-->
                    
                      </div><!--.gallery-->
                      <!-- Gallery -->
                      
                     </div><!--.col-->

        <!--Produktinfos-->
        <div class="col-lg-4 col-md4 col-sm-12 col-xs-12">
                <h4>Produktname</h4>
                    <div class="preis-flex">
                        <h5><b>12,99 € </b></h5>
                        <p class="mehrwertsteuer">&nbsp;inkl. MwSt.</p>
                    </div>
                    <p class="verfuegbar">Artikel online sofort verfügbar</p>
                <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna 
                    aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. 
                    Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 
                    Lorem ipsum dolor sit amet, consetetur sadipscing elitr</p>
                <button type="submit" class="btn btn-success">In die Einkauftasche</button>
        </div>
        <!--Produktinfos-->

     

    </div>   
   
</div>
</div>



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="../js/Produkt.js"></script>
</body>
</html>